version: 2
jobs:
  prod-build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: pull all
          command: git submodule update --init --recursive
      # generate config
      - run:
          name: generate config
          command: |
            cat > appconfig.json <<EOF
            {
              "DEBUG": false,
              "MINIFY": true,
              "SRI": true,
              "SENTRY_TRACKING_URL": "https://a62c2cb63e34460793d068c459b92090@sentry.io/1433278",
              "STATICSDIR": null,
              "GOOGLEADWORDS_ID": 875536627,
              "GOOGLEADWORDS_LABEL": "w2zkCO7L7WkQ88G-oQM",
              "API_HOST": "wallet-api.btc.com",
              "GOOGLE_RECAPTCHA_SITE_KEY": "6Lej1ZgUAAAAACLXn4ZqmeqdgEi-tTrZbV2TFeGl",
              "GOOGLEANALYTICS_ID": "UA-66176065-16",
              "GOOGLEANALYTICS_GLOBAL_ID": "UA-66176065-27",
              "FALLBACK_LANGUAGE": "en",
              "NULL": null
            }
            EOF

      # Download and cache dependencies
      - run: sudo npm install -g gulp
      - run: npm install gulp
      - run: npm install
      - run: gulp
      - run: sudo apt install python-pip python-dev -y;sudo pip install awscli
      - run:
          name: sync to aws
          command: |
            ## shame on you CircleCi
            AWS_ACCESS_KEY_ID=$MY_AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$MY_AWS_SECRET_ACCESS_KEY aws s3 sync www s3://$PROD_CDN

  dev-build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: pull all
          command: git submodule update --init --recursive
      # generate config
      - run:
          name: generate config
          command: |
                    cat > appconfig.json <<EOF
                    {
                      "DEBUG": false,
                      "MINIFY": true,
                      "SRI": true,
                      "SENTRY_TRACKING_URL": "https://7a25ba8a64804e5584c72cc2da0fd595@sentry.io/1433280",
                      "STATICSDIR": null,
                      "GOOGLEADWORDS_ID": 875536627,
                      "GOOGLEADWORDS_LABEL": "w2zkCO7L7WkQ88G-oQM",
                      "API_HOST": "beta.wallet-api.btc.com",
                      "GOOGLEANALYTICS_ID": "UA-66176065-16",
                      "GOOGLEANALYTICS_GLOBAL_ID": "UA-66176065-27",
                      "GOOGLE_RECAPTCHA_SITE_KEY": "6Ld51ZgUAAAAAEVY6MQg_rDpeW-ePZUPfBIXxqdG",
                      "FALLBACK_LANGUAGE": "en",
                      "NULL": null
                    }
                    EOF
                    cat appconfig.json

      # Download and cache dependencies
      - run: sudo npm install -g gulp
      - run: npm install gulp
      - run: npm install
      - run: gulp
      - run: sudo apt install python-pip python-dev -y;sudo pip install awscli
      - run:
          name: sync to aws
          command: |
            ## shame on you CircleCi
            AWS_ACCESS_KEY_ID=$MY_AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$MY_AWS_SECRET_ACCESS_KEY aws s3 sync www s3://$DEV_CDN

workflows:
  version: 2
  build-deploy:
    jobs:
      - dev-build:
          filters:
            branches:
              only: dev

      - prod-build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+/